version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clientes_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    environment:
      PG_HOST: db
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_DATABASE: clientes_db
      PG_DATABASE_TEST: clientes_test_db
    ports:
      - "3000:3000"
    command: ["npm", "run", "migrate", "&&", "npm", "start"]

  ci:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      PG_HOST: db
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_DATABASE: clientes_test_db
      NODE_ENV: test
    command: >
      sh -c "npm install &&
             npx knex migrate:latest --env test &&
             npm test"

volumes:
  pgdata:
